git: 
  depth: 5
jobs: 
  include: 
    - 
      before_script: 
        - "cd sample-application-backend"
      jdk: oraclejdk11
      language: java
      stage: "Build and test Java"
    - 
      before_script: 
        - "cd sample-application-frontend"
      language: node.js
      stage: "Build ans Test Nodejs"
cache :
  directories :
    - "$HOME/.m2/repository"
    - "$HOME/.npm"